export const defaultImages: { [key: string]: any } = {
  Netflix: require("@/assets/images/netflix_logo.png"),
  Spotify: require("@/assets/images/spotify_logo.png"),
  Youtube: require("@/assets/images/youtube_logo.png"),
  Prime: require("@/assets/images/PrimeVideo_logo.png"),
  Photoshop: require("@/assets/images/photoshop_logo.png"),
  Tidal: require("@/assets/images/tidal_logo.png"),
  Todoist: require("@/assets/images/todoist_logo.png"),
  Jetbrains: require("@/assets/images/jetbrains_logo.png"),
  Midjourney: require("@/assets/images/midjourney_logo.png"),
  HboMax: require("@/assets/images/hbomax_logo.png"),
  Indesign: require("@/assets/images/indesign_logo.png"),
  Figma: require("@/assets/images/figma_logo.png"),
  Filmora: require("@/assets/images/filmora_logo.png"),
  Grammarly: require("@/assets/images/grammarly_logo.png"),
  Coreldraw: require("@/assets/images/coreldraw_logo.png"),
  Evernote: require("@/assets/images/evernote_logo.png"),
  VSCode: require("@/assets/images/VSCode_Logo.png"),
  Affinity: require("@/assets/images/affinity_logo.png"),
  Illustrator: require("@/assets/images/ai_logo.png"),
  ChatGPT: require("@/assets/images/chatgpt_logo.png"),
  Copyai: require("@/assets/images/copyai_logo.png"),
  Notion: require("@/assets/images/Notion_logo.png"),
  "Premiere Pro": require("@/assets/images/Pr_Logo.png"),
  Github: require("@/assets/images/Github_logo.png"),
  Lightroom: require("@/assets/images/Lightroom_Logo.png"),
  "Microsoft 365": require("@/assets/images/Microsoft_365_logo.png"),
  "Final Cut Pro": require("@/assets/images/FinalCut_logo.png"),
  "Disney Plus": require("@/assets/images/DisneyPlus_Logo.png"),
  "Davinci Resolve": require("@/assets/images/Davinci_logo.png"),
  Canva: require("@/assets/images/Canva_logo.png"),
  Apple: require("@/assets/images/Apple_Logo.png"),
  // Add more mappings as needed
};
